#!/bin/zsh
echo "==== update_winddb_mirror ======================"
echo "Executing on $(date)"

. /ivohf/qdu/scripts/update_winddb_mirror/tables

chinaetfpchredmlist
chinamutualfundshare
cmftradingsuspension
chinamutualfundnav
suspendsecvaluation
suspendsecvaluationmethod
chinaetfpchredmmembers

echo "Program finished on $(date)"
