#!/bin/zsh
echo "==== update_winddb_mirror ======================"
echo "Executing on $(date)"

. ${0:a:h}/tables

chinaetfpchredmlist
chinamutualfundshare
cmftradingsuspension
chinamutualfundnav
suspendsecvaluation
suspendsecvaluationmethod
chinaetfpchredmmembers

echo "Program finished on $(date)"
