#!/bin/zsh
echo "==== update_winddb_mirror ======================"
echo "Executing on $(date)"

. /ivohf/qdu/scripts/update_winddb_mirror/tables

chinaetfpchredmlist
chinaetfpchredmmembers
chinamutualfundnav
suspendsecvaluation
suspendsecvaluationmethod

echo "Program finished on $(date)"
