#!/bin/zsh
echo "==== update_winddb_mirror ======================"
echo "Executing on $(date)"

. ${0:a:h}/tables

chinaetfpchredmlist
chinaetfpchredmmembers
chinamutualfundnav
suspendsecvaluation
suspendsecvaluationmethod

echo "Program finished on $(date)"
