#!/bin/zsh
echo "==== update_winddb_mirror ======================"
echo "Executing on $(date)"

. ${0:a:h}/tables

ashareseo

echo "Sucessfully updated all tables."
echo "Program finished on $(date)"
